# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e402f438c4baeb0595e1d1c2769be9244d055e946e989e0e43f7add7d1a076d87caaa52d12d7379c828d518b7f7cc48e18c5557558a70fb862ea777e59bf5463

test:
  secret_key_base: 238e0b050435164163777160500f9ddafefbf791d73cf3a2e7aa40cdd7897f0b769c75947c5c4a0c94c12476e7522d3b885a05445a57290ceca9f2ec80e90a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
